// Licensed under the Apache License, Version 2.0
// http://www.apache.org/licenses/LICENSE-2.0.html
//
// AUTOGENERATED BY H2O at 2015-09-18T12:55:16.562-07:00
// 3.2.0.1
//
// Standalone prediction code with sample test data for GBMModel named MyModel
//
// How to download, compile and execute:
//     mkdir tmpdir
//     cd tmpdir
//     curl http://127.0.0.1:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
//     curl http://127.0.0.1:54321/3/Models.java/MyModel > MyModel.java
//     javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m MyModel.java
//
//     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
import java.util.Map;
import hex.genmodel.GenModel;

public class MyModel extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Binomial; }

  public boolean isSupervised() { return true; }
  public int nfeatures() { return 4; }
  public int nclasses() { return 2; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_MyModel.VALUES;
  // Number of output classes included in training data response column.
  public static final int NCLASSES = 2;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* pclass */ MyModel_ColInfo_0.VALUES,
    /* sex */ MyModel_ColInfo_1.VALUES,
    /* age */ null,
    /* fare */ null,
    /* survived */ MyModel_ColInfo_4.VALUES
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = {0.6180290297937356,0.3819709702062643};
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = {0.6180290297937356,0.3819709702062643};

  public MyModel() { super(NAMES,DOMAINS); }
  public String getUUID() { return Long.toString(6876081621247217792L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    java.util.Arrays.fill(preds,0);
    double[] fdata = hex.genmodel.GenModel.SharedTree_clean(data);
    MyModel_Forest_0.score0(fdata,preds);
    MyModel_Forest_1.score0(fdata,preds);
    MyModel_Forest_2.score0(fdata,preds);
    MyModel_Forest_3.score0(fdata,preds);
    MyModel_Forest_4.score0(fdata,preds);
    MyModel_Forest_5.score0(fdata,preds);
    MyModel_Forest_6.score0(fdata,preds);
    MyModel_Forest_7.score0(fdata,preds);
    MyModel_Forest_8.score0(fdata,preds);
    MyModel_Forest_9.score0(fdata,preds);
    MyModel_Forest_10.score0(fdata,preds);
    MyModel_Forest_11.score0(fdata,preds);
    MyModel_Forest_12.score0(fdata,preds);
    MyModel_Forest_13.score0(fdata,preds);
    MyModel_Forest_14.score0(fdata,preds);
    MyModel_Forest_15.score0(fdata,preds);
    MyModel_Forest_16.score0(fdata,preds);
    MyModel_Forest_17.score0(fdata,preds);
    MyModel_Forest_18.score0(fdata,preds);
    MyModel_Forest_19.score0(fdata,preds);
    MyModel_Forest_20.score0(fdata,preds);
    MyModel_Forest_21.score0(fdata,preds);
    MyModel_Forest_22.score0(fdata,preds);
    MyModel_Forest_23.score0(fdata,preds);
    MyModel_Forest_24.score0(fdata,preds);
    MyModel_Forest_25.score0(fdata,preds);
    MyModel_Forest_26.score0(fdata,preds);
    MyModel_Forest_27.score0(fdata,preds);
    MyModel_Forest_28.score0(fdata,preds);
    MyModel_Forest_29.score0(fdata,preds);
    MyModel_Forest_30.score0(fdata,preds);
    MyModel_Forest_31.score0(fdata,preds);
    MyModel_Forest_32.score0(fdata,preds);
    MyModel_Forest_33.score0(fdata,preds);
    MyModel_Forest_34.score0(fdata,preds);
    MyModel_Forest_35.score0(fdata,preds);
    MyModel_Forest_36.score0(fdata,preds);
    MyModel_Forest_37.score0(fdata,preds);
    MyModel_Forest_38.score0(fdata,preds);
    MyModel_Forest_39.score0(fdata,preds);
    MyModel_Forest_40.score0(fdata,preds);
    MyModel_Forest_41.score0(fdata,preds);
    MyModel_Forest_42.score0(fdata,preds);
    MyModel_Forest_43.score0(fdata,preds);
    MyModel_Forest_44.score0(fdata,preds);
    MyModel_Forest_45.score0(fdata,preds);
    MyModel_Forest_46.score0(fdata,preds);
    MyModel_Forest_47.score0(fdata,preds);
    MyModel_Forest_48.score0(fdata,preds);
    MyModel_Forest_49.score0(fdata,preds);
    preds[2] = preds[1] + -0.48119081863629987;
    preds[2] = 1/(1+Math.min(1.7848230096318725E8, Math.exp(-preds[2])));
    preds[1] = 1.0-preds[2];
    preds[0] = hex.genmodel.GenModel.getPrediction(preds, PRIOR_CLASS_DISTRIB, data, 0.39901132722276156);
    return preds;
  }
}
// The class representing training column names
class NamesHolder_MyModel implements java.io.Serializable {
  public static final String[] VALUES = new String[4];
  static {
    NamesHolder_MyModel_0.fill(VALUES);
  }
  static final class NamesHolder_MyModel_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "pclass";
      sa[1] = "sex";
      sa[2] = "age";
      sa[3] = "fare";
    }
  }
}
// The class representing column pclass
class MyModel_ColInfo_0 implements java.io.Serializable {
  public static final String[] VALUES = new String[3];
  static {
    MyModel_ColInfo_0_0.fill(VALUES);
  }
  static final class MyModel_ColInfo_0_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "1";
      sa[1] = "2";
      sa[2] = "3";
    }
  }
}
// The class representing column sex
class MyModel_ColInfo_1 implements java.io.Serializable {
  public static final String[] VALUES = new String[2];
  static {
    MyModel_ColInfo_1_0.fill(VALUES);
  }
  static final class MyModel_ColInfo_1_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "female";
      sa[1] = "male";
    }
  }
}
// The class representing column survived
class MyModel_ColInfo_4 implements java.io.Serializable {
  public static final String[] VALUES = new String[2];
  static {
    MyModel_ColInfo_4_0.fill(VALUES);
  }
  static final class MyModel_ColInfo_4_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "0";
      sa[1] = "1";
    }
  }
}

class MyModel_Forest_0 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_0_class_0.score0(fdata);
  }
}
class MyModel_Tree_0_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[3 /* fare */] <32.42395f
          ? (data[2 /* age */] <35.52541f
            ? (data[3 /* fare */] <26.056488f ? 0.20337178f : 0.26180002f)
            : (data[3 /* fare */] <25.725498f ? 0.20128506f : 0.15589884f))
          : (data[3 /* fare */] <148.65102f
            ? 0.26180002f
            : (data[3 /* fare */] <222.52316f ? 0.18704624f : 0.26180002f)))
        : (data[3 /* fare */] <24.524271f
          ? (data[2 /* age */] <24.465519f
            ? (data[3 /* fare */] <8.109375f ? 0.1270167f : 0.06491332f)
            : (data[3 /* fare */] <15.721875f ? -0.009741469f : 0.085298054f))
          : (data[3 /* fare */] <32.9666f ? -0.105324075f : -0.1618047f)))
      : (data[0 /* pclass */] <0.5f
        ? (data[2 /* age */] <54.481766f
          ? (data[2 /* age */] <47.57689f
            ? (data[2 /* age */] <45.389694f ? 0.0061764806f : -0.1618047f)
            : (data[3 /* fare */] <56.036015f ? 0.085298054f : 0.030742899f))
          : (data[2 /* age */] <60.462605f ? -0.096634746f : -0.13356438f))
        : (data[2 /* age */] <32.231102f
          ? (data[2 /* age */] <31.608099f
            ? (data[3 /* fare */] <9.187501f ? -0.104723215f : -0.07282837f)
            : 0.0076371864f)
          : (data[3 /* fare */] <18.94922f
            ? (data[3 /* fare */] <7.698121f ? -0.1618047f : -0.12372787f)
            : -0.1618047f))));
    return pred;
  }
}

class MyModel_Forest_1 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_1_class_0.score0(fdata);
  }
}
class MyModel_Tree_1_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[3 /* fare */] <32.42395f
          ? (data[2 /* age */] <35.52541f
            ? (data[3 /* fare */] <26.056488f ? 0.17578085f : 0.22453177f)
            : (data[3 /* fare */] <25.725498f ? 0.17403108f : 0.13577472f))
          : (data[3 /* fare */] <148.65102f
            ? 0.22453177f
            : (data[3 /* fare */] <222.52316f ? 0.16207168f : 0.22453177f)))
        : (data[3 /* fare */] <24.524271f
          ? (data[2 /* age */] <16.611355f
            ? (data[2 /* age */] <11.472401f ? 0.08911786f : 0.17044176f)
            : (data[3 /* fare */] <7.565625f ? 0.16723952f : 0.018868048f))
          : (data[3 /* fare */] <32.9666f ? -0.09757326f : -0.15257153f)))
      : (data[0 /* pclass */] <0.5f
        ? (data[2 /* age */] <54.481766f
          ? (data[2 /* age */] <47.57689f
            ? (data[2 /* age */] <45.389694f ? 0.005550331f : -0.15257153f)
            : (data[3 /* fare */] <56.036015f ? 0.07528814f : 0.027463805f))
          : (data[2 /* age */] <60.462605f ? -0.08929209f : -0.124810815f))
        : (data[2 /* age */] <32.231102f
          ? (data[2 /* age */] <31.608099f
            ? (data[3 /* fare */] <9.187501f ? -0.09699915f : -0.0668316f)
            : 0.0068604937f)
          : (data[3 /* fare */] <18.94922f
            ? (data[3 /* fare */] <7.698121f ? -0.15257153f : -0.11526607f)
            : -0.15257153f))));
    return pred;
  }
}

class MyModel_Forest_2 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_2_class_0.score0(fdata);
  }
}
class MyModel_Tree_2_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[3 /* fare */] <32.42395f
          ? (data[2 /* age */] <35.52541f
            ? (data[3 /* fare */] <26.056488f ? 0.15542643f : 0.19948722f)
            : (data[3 /* fare */] <25.725498f ? 0.15386511f : 0.119965985f))
          : (data[3 /* fare */] <148.65102f
            ? 0.19948722f
            : (data[2 /* age */] <27.953129f ? 0.12518501f : 0.19030759f)))
        : (data[3 /* fare */] <24.524271f
          ? (data[2 /* age */] <27.410831f
            ? (data[3 /* fare */] <15.450001f ? 0.059164293f : 0.115383975f)
            : (data[2 /* age */] <30.747316f ? -0.07387285f : 0.035292473f))
          : (data[2 /* age */] <3.3574538f ? -0.14808765f : -0.09424152f)))
      : (data[0 /* pclass */] <0.5f
        ? (data[2 /* age */] <54.481766f
          ? (data[2 /* age */] <47.57689f
            ? (data[2 /* age */] <45.389694f ? 0.0049885176f : -0.14513253f)
            : (data[3 /* fare */] <56.036015f ? 0.06680978f : 0.024563782f))
          : (data[3 /* fare */] <42.027008f ? -0.08465776f : -0.11728731f))
        : (data[2 /* age */] <32.231102f
          ? (data[2 /* age */] <31.608099f
            ? (data[3 /* fare */] <13.781251f ? -0.08653194f : -0.0546389f)
            : 0.0061641335f)
          : (data[3 /* fare */] <18.94922f
            ? (data[2 /* age */] <36.390625f ? -0.13567531f : -0.10529666f)
            : -0.14513253f))));
    return pred;
  }
}

class MyModel_Forest_3 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_3_class_0.score0(fdata);
  }
}
class MyModel_Tree_3_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[3 /* fare */] <32.42395f
          ? (data[2 /* age */] <21.447292f
            ? (data[3 /* fare */] <21.919125f ? 0.12202208f : 0.18744089f)
            : (data[2 /* age */] <27.431267f ? 0.10272239f : 0.14307582f))
          : (data[3 /* fare */] <148.65102f
            ? 0.18149503f
            : (data[3 /* fare */] <222.52316f ? 0.12520333f : 0.18432882f)))
        : (data[3 /* fare */] <24.524271f
          ? (data[2 /* age */] <27.410831f
            ? (data[3 /* fare */] <7.8375f ? 0.09683358f : 0.049349643f)
            : (data[3 /* fare */] <15.721875f ? -0.032281347f : 0.07851434f))
          : (data[3 /* fare */] <32.9666f ? -0.082631685f : -0.14025705f)))
      : (data[0 /* pclass */] <0.5f
        ? (data[2 /* age */] <54.481766f
          ? (data[2 /* age */] <36.48725f
            ? (data[2 /* age */] <33.430405f ? -0.0018337342f : 0.14403674f)
            : (data[2 /* age */] <47.569542f ? -0.059821777f : 0.041793354f))
          : (data[2 /* age */] <60.462605f ? -0.075236864f : -0.11155696f))
        : (data[2 /* age */] <32.231102f
          ? (data[2 /* age */] <0.5825016f
            ? (data[3 /* fare */] <21.820314f ? -0.10222641f : -0.01108127f)
            : (data[2 /* age */] <9.664123f ? 0.097118214f : -0.076175995f))
          : (data[3 /* fare */] <18.94922f
            ? (data[3 /* fare */] <7.698121f ? -0.14025529f : -0.10075589f)
            : -0.13903546f))));
    return pred;
  }
}

class MyModel_Forest_4 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_4_class_0.score0(fdata);
  }
}
class MyModel_Tree_4_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[3 /* fare */] <32.42395f
          ? (data[2 /* age */] <35.52541f
            ? (data[3 /* fare */] <12.816923f ? 0.18354075f : 0.1299157f)
            : (data[2 /* age */] <44.64618f ? 0.08633151f : 0.12196526f))
          : (data[3 /* fare */] <148.65102f
            ? 0.16796868f
            : (data[2 /* age */] <27.953129f ? 0.098118335f : 0.15914162f)))
        : (data[3 /* fare */] <24.524271f
          ? (data[3 /* fare */] <7.374877f
            ? 0.14971527f
            : (data[2 /* age */] <27.656273f ? 0.055143714f : -0.0317406f))
          : (data[2 /* age */] <3.3574538f ? -0.13734661f : -0.08100226f)))
      : (data[0 /* pclass */] <0.5f
        ? (data[2 /* age */] <53.548172f
          ? (data[2 /* age */] <47.586014f
            ? (data[2 /* age */] <45.398388f ? 0.004708679f : -0.13676877f)
            : (data[3 /* fare */] <56.036015f ? 0.061810445f : 0.03642347f))
          : (data[3 /* fare */] <56.036015f ? -0.067160614f : -0.10574479f))
        : (data[2 /* age */] <32.231102f
          ? (data[2 /* age */] <31.608099f
            ? (data[3 /* fare */] <60.867195f ? -0.06436244f : -0.14839488f)
            : 0.013334181f)
          : (data[2 /* age */] <36.310097f
            ? (data[0 /* pclass */] <1.5f ? -0.10661882f : -0.1371547f)
            : (data[2 /* age */] <39.549072f ? -0.05242245f : -0.11234566f)))));
    return pred;
  }
}

class MyModel_Forest_5 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_5_class_0.score0(fdata);
  }
}
class MyModel_Tree_5_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[3 /* fare */] <32.42395f
          ? (data[2 /* age */] <49.310234f
            ? (data[3 /* fare */] <12.816923f ? 0.16953391f : 0.11705662f)
            : 0.08423623f)
          : (data[3 /* fare */] <148.65102f
            ? 0.15745938f
            : (data[3 /* fare */] <222.52316f ? 0.10089091f : 0.16133346f)))
        : (data[3 /* fare */] <22.549353f
          ? (data[3 /* fare */] <7.2437296f
            ? 0.16319878f
            : (data[3 /* fare */] <14.801015f ? 0.01590075f : 0.09019117f))
          : (data[2 /* age */] <5.3209944f ? -0.03846407f : -0.1140315f)))
      : (data[0 /* pclass */] <0.5f
        ? (data[3 /* fare */] <26.016722f
          ? -0.09415076f
          : (data[2 /* age */] <53.432957f
            ? (data[3 /* fare */] <33.881905f ? 0.066263005f : -0.011300237f)
            : (data[3 /* fare */] <56.665108f ? -0.057956558f : -0.09979369f)))
        : (data[2 /* age */] <32.231102f
          ? (data[2 /* age */] <0.5825016f
            ? (data[3 /* fare */] <21.820314f ? -0.09193357f : -0.001152584f)
            : (data[2 /* age */] <9.664123f ? 0.09284489f : -0.06612016f))
          : (data[3 /* fare */] <18.94922f
            ? (data[3 /* fare */] <10.066773f ? -0.10990463f : -0.07770315f)
            : (data[2 /* age */] <39.632812f ? -0.13110718f : -0.13035889f)))));
    return pred;
  }
}

class MyModel_Forest_6 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_6_class_0.score0(fdata);
  }
}
class MyModel_Tree_6_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[2 /* age */] <56.44923f
          ? (data[3 /* fare */] <22.261623f
            ? (data[3 /* fare */] <19.045555f ? 0.1210592f : 0.03996019f)
            : (data[3 /* fare */] <152.43585f ? 0.13534226f : 0.15820551f))
          : 0.07571597f)
        : (data[3 /* fare */] <24.524271f
          ? (data[2 /* age */] <16.611355f
            ? (data[2 /* age */] <11.472401f ? 0.053598832f : 0.12394405f)
            : (data[3 /* fare */] <7.565625f ? 0.112900116f : 0.0033835121f))
          : (data[2 /* age */] <3.3574538f ? -0.13133986f : -0.06871919f)))
      : (data[0 /* pclass */] <0.5f
        ? (data[3 /* fare */] <26.016722f
          ? -0.08695939f
          : (data[2 /* age */] <53.432957f
            ? (data[3 /* fare */] <33.881905f ? 0.05880533f : -0.01019916f)
            : (data[2 /* age */] <60.48983f ? -0.05136053f : -0.09464579f)))
        : (data[2 /* age */] <32.231102f
          ? (data[2 /* age */] <31.608099f
            ? (data[3 /* fare */] <60.867195f ? -0.055191863f : -0.1401554f)
            : 0.018846253f)
          : (data[2 /* age */] <45.283886f
            ? (data[2 /* age */] <36.295216f ? -0.11697267f : -0.072161354f)
            : (data[2 /* age */] <60.76367f ? -0.13053863f : -0.076174684f)))));
    return pred;
  }
}

class MyModel_Forest_7 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_7_class_0.score0(fdata);
  }
}
class MyModel_Tree_7_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[3 /* fare */] <26.499191f
          ? (data[2 /* age */] <43.151062f
            ? (data[2 /* age */] <30.612848f ? 0.08915302f : 0.1365861f)
            : 0.06468441f)
          : (data[3 /* fare */] <147.95671f
            ? (data[3 /* fare */] <28.44698f ? 0.15583232f : 0.13606562f)
            : (data[2 /* age */] <27.899763f ? 0.06612475f : 0.13080744f)))
        : (data[3 /* fare */] <22.549353f
          ? (data[3 /* fare */] <15.6371355f
            ? (data[3 /* fare */] <14.248521f ? 0.035088636f : -0.04638795f)
            : (data[3 /* fare */] <17.579971f ? 0.14975086f : 0.04650386f))
          : (data[2 /* age */] <5.3209944f ? -0.030560454f : -0.106068544f)))
      : (data[3 /* fare */] <52.033443f
        ? (data[3 /* fare */] <39.63485f
          ? (data[3 /* fare */] <35.299786f
            ? (data[0 /* pclass */] <0.5f ? -0.0038658746f : -0.060118668f)
            : 0.09960469f)
          : (data[2 /* age */] <37.988266f
            ? (data[0 /* pclass */] <0.5f ? -0.16268161f : -0.1473547f)
            : -0.11133922f))
        : (data[3 /* fare */] <59.225567f
          ? 0.1661802f
          : (data[3 /* fare */] <80.464806f
            ? (data[3 /* fare */] <76.02145f ? -0.1074678f : -0.021117173f)
            : (data[3 /* fare */] <141.19574f ? 0.053279072f : -0.05877556f)))));
    return pred;
  }
}

class MyModel_Forest_8 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_8_class_0.score0(fdata);
  }
}
class MyModel_Tree_8_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[2 /* age */] <56.44923f
          ? (data[3 /* fare */] <22.261623f
            ? (data[2 /* age */] <27.597675f ? 0.052853774f : 0.119027704f)
            : (data[3 /* fare */] <152.43585f ? 0.1211457f : 0.14451784f))
          : 0.059800245f)
        : (data[3 /* fare */] <24.524271f
          ? (data[2 /* age */] <16.611355f
            ? (data[3 /* fare */] <15.450001f ? 0.0388146f : 0.08947481f)
            : (data[3 /* fare */] <7.565625f ? 0.09925768f : -9.141603E-4f))
          : (data[2 /* age */] <3.3574538f ? -0.12666567f : -0.057534896f)))
      : (data[3 /* fare */] <52.033443f
        ? (data[3 /* fare */] <39.63485f
          ? (data[3 /* fare */] <26.01037f
            ? (data[2 /* age */] <32.697903f ? -0.046724323f : -0.09031379f)
            : (data[0 /* pclass */] <1.5f ? 0.02591629f : -0.114756465f))
          : (data[2 /* age */] <37.988266f
            ? (data[0 /* pclass */] <0.5f ? -0.15327922f : -0.14093469f)
            : -0.1043124f))
        : (data[3 /* fare */] <59.225567f
          ? 0.14336461f
          : (data[0 /* pclass */] <0.5f
            ? (data[2 /* age */] <21.425806f ? 0.087117575f : -0.035979107f)
            : -0.1324049f))));
    return pred;
  }
}

class MyModel_Forest_9 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_9_class_0.score0(fdata);
  }
}
class MyModel_Tree_9_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[3 /* fare */] <32.42395f
          ? (data[2 /* age */] <21.447292f
            ? (data[3 /* fare */] <21.919125f ? 0.06766173f : 0.13940938f)
            : (data[2 /* age */] <27.431267f ? 0.045861244f : 0.085234955f))
          : (data[3 /* fare */] <148.65102f
            ? (data[2 /* age */] <54.906258f ? 0.13315076f : 0.13659994f)
            : (data[3 /* fare */] <222.52316f ? 0.06259021f : 0.1355961f)))
        : (data[3 /* fare */] <22.549353f
          ? (data[3 /* fare */] <7.2437296f
            ? 0.1296562f
            : (data[3 /* fare */] <14.801015f ? 0.0061741234f : 0.06822818f))
          : (data[2 /* age */] <5.3209944f ? -0.02514916f : -0.09958467f)))
      : (data[3 /* fare */] <52.033443f
        ? (data[3 /* fare */] <39.63485f
          ? (data[3 /* fare */] <35.299786f
            ? (data[0 /* pclass */] <0.5f ? -0.0037833322f : -0.05181437f)
            : 0.08347753f)
          : (data[2 /* age */] <37.988266f
            ? (data[0 /* pclass */] <0.5f ? -0.14571434f : -0.13560683f)
            : -0.09793393f))
        : (data[3 /* fare */] <59.225567f
          ? 0.12576838f
          : (data[3 /* fare */] <80.464806f
            ? (data[3 /* fare */] <76.02145f ? -0.097779505f : -0.017007602f)
            : (data[3 /* fare */] <141.19574f ? 0.048446033f : -0.05406558f)))));
    return pred;
  }
}

class MyModel_Forest_10 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_10_class_0.score0(fdata);
  }
}
class MyModel_Tree_10_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[2 /* age */] <56.44923f
          ? (data[3 /* fare */] <34.023247f
            ? (data[3 /* fare */] <12.705304f ? 0.14171268f : 0.07973715f)
            : (data[2 /* age */] <2.6380534f ? 0.08043524f : 0.12618305f))
          : 0.046336006f)
        : (data[3 /* fare */] <22.549353f
          ? (data[3 /* fare */] <7.7374597f
            ? (data[3 /* fare */] <7.2668734f ? 0.12442244f : 0.04921852f)
            : (data[3 /* fare */] <14.81943f ? -0.0014519824f : 0.061525412f))
          : (data[3 /* fare */] <33.014343f
            ? (data[2 /* age */] <5.59375f ? 0.0063842954f : -0.07767307f)
            : -0.12094537f)))
      : (data[3 /* fare */] <15.009647f
        ? (data[2 /* age */] <0.6444981f
          ? (data[3 /* fare */] <8.085938f
            ? (data[3 /* fare */] <6.9488535f ? -0.13512884f : -0.08287985f)
            : -0.006577109f)
          : (data[2 /* age */] <15.544835f
            ? 0.2064122f
            : (data[3 /* fare */] <8.203126f ? -0.03948644f : -0.069513805f)))
        : (data[2 /* age */] <9.513643f
          ? (data[0 /* pclass */] != 1.0f
            ? (data[3 /* fare */] <18.365788f ? 0.0773188f : -0.020053813f)
            : 0.20773114f)
          : (data[0 /* pclass */] <0.5f
            ? (data[2 /* age */] <36.250004f ? 0.03458735f : -0.031446915f)
            : (data[2 /* age */] <25.312502f ? -0.1152988f : -0.06417075f)))));
    return pred;
  }
}

class MyModel_Forest_11 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_11_class_0.score0(fdata);
  }
}
class MyModel_Tree_11_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[2 /* age */] <56.44923f
          ? (data[3 /* fare */] <22.261623f
            ? (data[3 /* fare */] <19.045555f ? 0.089366555f : 0.0038220384f)
            : (data[3 /* fare */] <152.43585f ? 0.105416596f : 0.1309476f))
          : 0.042611085f)
        : (data[3 /* fare */] <22.549353f
          ? (data[2 /* age */] <16.611355f
            ? (data[2 /* age */] <3.5070205f ? 0.03196005f : 0.094365306f)
            : (data[3 /* fare */] <7.7255187f ? 0.07806035f : -0.0060962043f))
          : (data[3 /* fare */] <33.014343f
            ? (data[2 /* age */] <5.59375f ? 0.005734425f : -0.072925925f)
            : -0.11855936f)))
      : (data[3 /* fare */] <52.033443f
        ? (data[3 /* fare */] <39.63485f
          ? (data[3 /* fare */] <28.332724f
            ? (data[3 /* fare */] <26.56193f ? -0.04105024f : -0.11307473f)
            : (data[0 /* pclass */] <1.5f ? 0.046038847f : -0.098341316f))
          : (data[2 /* age */] <37.988266f
            ? (data[0 /* pclass */] <0.5f ? -0.14007807f : -0.12965791f)
            : -0.090133175f))
        : (data[3 /* fare */] <59.225567f
          ? 0.11376856f
          : (data[3 /* fare */] <80.464806f
            ? (data[3 /* fare */] <76.02145f ? -0.091156214f : -0.015176736f)
            : (data[3 /* fare */] <141.19574f ? 0.043426413f : -0.04984133f)))));
    return pred;
  }
}

class MyModel_Forest_12 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_12_class_0.score0(fdata);
  }
}
class MyModel_Tree_12_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[3 /* fare */] <32.42395f
          ? (data[2 /* age */] <35.52541f
            ? (data[2 /* age */] <30.38818f ? 0.069217175f : 0.13386054f)
            : (data[2 /* age */] <44.64618f ? 0.012409236f : 0.059432417f))
          : (data[3 /* fare */] <148.65102f
            ? (data[2 /* age */] <54.906258f ? 0.12316156f : 0.12863798f)
            : (data[2 /* age */] <27.953129f ? 0.020744199f : 0.10354041f)))
        : (data[3 /* fare */] <24.524271f
          ? (data[2 /* age */] <27.410831f
            ? (data[3 /* fare */] <8.109375f ? 0.05244517f : 0.00884958f)
            : (data[3 /* fare */] <12.323438f ? -0.060940083f : 0.027339017f))
          : (data[2 /* age */] <3.3574538f ? -0.12155236f : -0.03412306f)))
      : (data[3 /* fare */] <15.009647f
        ? (data[2 /* age */] <0.6444981f
          ? (data[3 /* fare */] <8.085938f
            ? (data[3 /* fare */] <7.833253f ? -0.066672355f : -0.11008441f)
            : -0.0019236528f)
          : (data[2 /* age */] <15.544835f
            ? 0.17734748f
            : (data[2 /* age */] <19.198284f ? -0.078788035f : -0.039106842f)))
        : (data[2 /* age */] <9.513643f
          ? (data[0 /* pclass */] != 1.0f
            ? (data[3 /* fare */] <18.365788f ? 0.072458975f : -0.01465413f)
            : 0.17647393f)
          : (data[0 /* pclass */] != 1.0f
            ? (data[2 /* age */] <38.437504f ? 0.0065219724f : -0.033367f)
            : (data[3 /* fare */] <30.5738f ? -0.09117959f : -0.12866686f)))));
    return pred;
  }
}

class MyModel_Forest_13 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_13_class_0.score0(fdata);
  }
}
class MyModel_Tree_13_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[2 /* age */] <56.44923f
          ? (data[2 /* age */] <2.4351676f
            ? 0.05526347f
            : (data[3 /* fare */] <34.023247f ? 0.07306202f : 0.11614931f))
          : 0.030742731f)
        : (data[3 /* fare */] <22.549353f
          ? (data[3 /* fare */] <15.6371355f
            ? (data[3 /* fare */] <14.248521f ? 0.021727236f : -0.056957938f)
            : (data[3 /* fare */] <17.579971f ? 0.11880601f : 0.021170653f))
          : (data[3 /* fare */] <31.361977f ? -0.06795429f : -0.007814238f)))
      : (data[3 /* fare */] <52.033443f
        ? (data[3 /* fare */] <39.63485f
          ? (data[3 /* fare */] <15.172715f
            ? (data[3 /* fare */] <13.987347f ? -0.03964521f : -0.10920982f)
            : (data[2 /* age */] <9.046845f ? 0.042128734f : -0.030294856f))
          : (data[2 /* age */] <37.988266f
            ? (data[0 /* pclass */] <0.5f ? -0.1348101f : -0.12571259f)
            : -0.08284747f))
        : (data[3 /* fare */] <59.225567f
          ? 0.102329195f
          : (data[2 /* age */] <17.377956f
            ? 0.045591693f
            : (data[3 /* fare */] <140.78574f ? -0.025011595f : -0.07783241f)))));
    return pred;
  }
}

class MyModel_Forest_14 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_14_class_0.score0(fdata);
  }
}
class MyModel_Tree_14_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[3 /* fare */] <26.499191f
          ? (data[2 /* age */] <43.151062f
            ? (data[2 /* age */] <30.612848f ? 0.04705582f : 0.10209642f)
            : 0.0167279f)
          : (data[3 /* fare */] <147.95671f
            ? (data[3 /* fare */] <28.44698f ? 0.12990515f : 0.10758154f)
            : (data[3 /* fare */] <221.96988f ? 0.025128473f : 0.1210043f)))
        : (data[3 /* fare */] <24.524271f
          ? (data[2 /* age */] <16.611355f
            ? (data[3 /* fare */] <15.450001f ? 0.022687152f : 0.06946837f)
            : (data[2 /* age */] <21.685114f ? -0.037996575f : 0.013642525f))
          : (data[2 /* age */] <3.3574538f ? -0.11811894f : -0.028752664f)))
      : (data[2 /* age */] <0.32262444f
        ? (data[3 /* fare */] <22.014149f
          ? (data[3 /* fare */] <15.392705f
            ? (data[3 /* fare */] <12.987596f ? -0.07406988f : 0.039586816f)
            : -0.1352458f)
          : (data[3 /* fare */] <40.478016f
            ? (data[3 /* fare */] <26.180428f ? 0.03622969f : -0.009503621f)
            : -0.04840668f))
        : (data[2 /* age */] <9.504198f
          ? (data[0 /* pclass */] <1.5f
            ? 0.23189422f
            : (data[3 /* fare */] <24.036625f ? 0.15415865f : -0.09807952f))
          : (data[0 /* pclass */] != 1.0f
            ? (data[2 /* age */] <19.84375f ? -0.059058007f : -0.014092545f)
            : (data[3 /* fare */] <16.01029f ? -0.05668192f : -0.09639567f)))));
    return pred;
  }
}

class MyModel_Forest_15 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_15_class_0.score0(fdata);
  }
}
class MyModel_Tree_15_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[2 /* age */] <56.44923f
          ? (data[2 /* age */] <2.4351676f
            ? 0.045252424f
            : (data[2 /* age */] <17.500278f ? 0.12276178f : 0.08218711f))
          : 0.020600097f)
        : (data[3 /* fare */] <32.42395f
          ? (data[3 /* fare */] <23.397953f
            ? (data[3 /* fare */] <15.594225f ? 0.0072860024f : 0.061678324f)
            : (data[2 /* age */] <5.075552f ? -0.036724772f : -0.06334262f))
          : -0.11450299f))
      : (data[0 /* pclass */] <0.5f
        ? (data[2 /* age */] <36.432278f
          ? (data[2 /* age */] <33.51889f
            ? (data[2 /* age */] <28.424799f ? 0.016616458f : -0.052020445f)
            : 0.13927287f)
          : (data[2 /* age */] <41.537872f
            ? -0.07076464f
            : (data[2 /* age */] <53.55729f ? 0.013474057f : -0.05696006f)))
        : (data[2 /* age */] <32.231102f
          ? (data[2 /* age */] <31.608099f
            ? (data[2 /* age */] <0.82196873f ? -0.048145097f : -0.01834711f)
            : 0.047171976f)
          : (data[3 /* fare */] <7.464844f
            ? (data[2 /* age */] <40.60547f ? -0.117435396f : -0.117453516f)
            : (data[3 /* fare */] <19.151674f ? -0.054358438f : -0.115388766f)))));
    return pred;
  }
}

class MyModel_Forest_16 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_16_class_0.score0(fdata);
  }
}
class MyModel_Tree_16_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[3 /* fare */] <32.42395f
          ? (data[2 /* age */] <21.447292f
            ? (data[3 /* fare */] <21.919125f ? 0.027254574f : 0.12127974f)
            : (data[2 /* age */] <27.431267f ? 7.652251E-4f : 0.047902588f))
          : (data[3 /* fare */] <148.65102f
            ? (data[2 /* age */] <54.906258f ? 0.11523037f : 0.12120182f)
            : (data[2 /* age */] <27.953129f ? -0.006940881f : 0.090165064f)))
        : (data[3 /* fare */] <32.42395f
          ? (data[2 /* age */] <27.410831f
            ? (data[3 /* fare */] <23.303322f ? 0.025451658f : -0.06361304f)
            : (data[3 /* fare */] <8.674805f ? -0.07501069f : 0.015008563f))
          : -0.11293642f))
      : (data[2 /* age */] <0.32262444f
        ? (data[3 /* fare */] <22.014149f
          ? (data[3 /* fare */] <15.392705f
            ? (data[3 /* fare */] <12.987596f ? -0.06753216f : 0.04062241f)
            : -0.1293768f)
          : (data[3 /* fare */] <40.478016f
            ? (data[3 /* fare */] <26.180428f ? 0.034752324f : -0.010204286f)
            : -0.042458616f))
        : (data[2 /* age */] <9.504198f
          ? (data[0 /* pclass */] <1.5f
            ? 0.20640723f
            : (data[3 /* fare */] <24.036625f ? 0.1354974f : -0.09195634f))
          : (data[0 /* pclass */] != 1.0f
            ? (data[2 /* age */] <19.84375f ? -0.054138135f : -0.011149772f)
            : (data[3 /* fare */] <32.02058f ? -0.058306526f : -0.121192545f)))));
    return pred;
  }
}

class MyModel_Forest_17 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_17_class_0.score0(fdata);
  }
}
class MyModel_Tree_17_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[2 /* age */] <56.44923f
          ? (data[3 /* fare */] <151.6395f
            ? (data[3 /* fare */] <133.99707f ? 0.07555368f : -0.008441305f)
            : (data[3 /* fare */] <224.9046f ? 0.12076215f : 0.11590191f))
          : 0.010472317f)
        : (data[3 /* fare */] <32.42395f
          ? (data[3 /* fare */] <7.351733f
            ? 0.07589106f
            : (data[2 /* age */] <27.656273f ? 0.01739691f : -0.03507377f))
          : -0.11155694f))
      : (data[3 /* fare */] <52.033443f
        ? (data[3 /* fare */] <39.63485f
          ? (data[3 /* fare */] <28.332724f
            ? (data[3 /* fare */] <26.56193f ? -0.02597668f : -0.09993815f)
            : (data[0 /* pclass */] <1.5f ? 0.04670412f : -0.08387177f))
          : (data[2 /* age */] <37.988266f
            ? (data[0 /* pclass */] <0.5f ? -0.12921901f : -0.11880684f)
            : -0.07547869f))
        : (data[3 /* fare */] <59.225567f
          ? 0.09848194f
          : (data[3 /* fare */] <80.464806f
            ? (data[3 /* fare */] <76.02145f ? -0.07954414f : -0.0090128165f)
            : (data[3 /* fare */] <141.19574f ? 0.040397752f : -0.040812857f)))));
    return pred;
  }
}

class MyModel_Forest_18 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_18_class_0.score0(fdata);
  }
}
class MyModel_Tree_18_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[3 /* fare */] <32.42395f
          ? (data[2 /* age */] <35.52541f
            ? (data[3 /* fare */] <12.816923f ? 0.12213874f : 0.042191368f)
            : (data[2 /* age */] <44.64618f ? -0.028052228f : 0.032507874f))
          : (data[3 /* fare */] <148.65102f
            ? (data[2 /* age */] <54.906258f ? 0.11266908f : 0.11857163f)
            : (data[3 /* fare */] <222.52316f ? 0.0039866325f : 0.11525284f)))
        : (data[2 /* age */] <5.4987288f
          ? (data[3 /* fare */] <23.431253f
            ? (data[3 /* fare */] <15.328127f ? 0.0016824228f : 0.10151743f)
            : -0.044413485f)
          : (data[3 /* fare */] <7.7312503f
            ? 0.079739906f
            : (data[2 /* age */] <14.906251f ? -0.11178783f : -0.004388644f))))
      : (data[2 /* age */] <0.32262444f
        ? (data[3 /* fare */] <22.014149f
          ? (data[3 /* fare */] <15.392705f
            ? (data[3 /* fare */] <12.987596f ? -0.062248267f : 0.038853645f)
            : -0.12517437f)
          : (data[3 /* fare */] <40.478016f
            ? (data[3 /* fare */] <26.180428f ? 0.033751667f : -0.010057772f)
            : -0.037807003f))
        : (data[2 /* age */] <9.504198f
          ? (data[0 /* pclass */] <1.5f
            ? 0.18687698f
            : (data[3 /* fare */] <24.036625f ? 0.1210774f : -0.082296506f))
          : (data[0 /* pclass */] <0.5f
            ? (data[2 /* age */] <36.250004f ? 0.035227094f : -0.019167922f)
            : (data[3 /* fare */] <8.005145f ? -0.016007762f : -0.046884436f)))));
    return pred;
  }
}

class MyModel_Forest_19 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_19_class_0.score0(fdata);
  }
}
class MyModel_Tree_19_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[3 /* fare */] <26.499191f
          ? (data[3 /* fare */] <20.312004f
            ? (data[3 /* fare */] <13.259626f ? 0.013051977f : 0.12707613f)
            : (data[2 /* age */] <27.375002f ? -0.027872866f : 0.046199005f))
          : (data[3 /* fare */] <147.95671f
            ? (data[3 /* fare */] <28.44698f ? 0.12189706f : 0.095539175f)
            : (data[2 /* age */] <27.899763f ? -0.020356523f : 0.0813017f)))
        : (data[3 /* fare */] <32.42395f
          ? (data[3 /* fare */] <7.351733f
            ? 0.06519275f
            : (data[2 /* age */] <27.656273f ? 0.015129614f : -0.031607267f))
          : -0.11000537f))
      : (data[3 /* fare */] <26.016722f
        ? (data[2 /* age */] <32.231102f
          ? (data[2 /* age */] <30.860495f
            ? (data[2 /* age */] <0.8102874f ? -0.03969813f : -0.0100835925f)
            : (data[3 /* fare */] <8.125001f ? 0.088996336f : -0.023558542f))
          : (data[3 /* fare */] <7.9218755f
            ? (data[2 /* age */] <48.386723f ? -0.11911742f : -0.04521319f)
            : (data[3 /* fare */] <18.938234f ? -0.022439934f : -0.12003172f)))
        : (data[2 /* age */] <54.481766f
          ? (data[2 /* age */] <47.566143f
            ? (data[2 /* age */] <45.37554f ? 0.0046958886f : -0.1258172f)
            : (data[3 /* fare */] <64.224945f ? 0.08770487f : 0.02215372f))
          : (data[3 /* fare */] <33.84499f ? -0.076837815f : -0.039294742f))));
    return pred;
  }
}

class MyModel_Forest_20 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_20_class_0.score0(fdata);
  }
}
class MyModel_Tree_20_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[2 /* age */] <56.44923f
          ? (data[3 /* fare */] <151.6395f
            ? (data[3 /* fare */] <12.705305f ? 0.12026359f : 0.055802133f)
            : (data[3 /* fare */] <224.9046f ? 0.11723202f : 0.11250959f))
          : -0.0062004253f)
        : (data[3 /* fare */] <32.42395f
          ? (data[2 /* age */] <16.611355f
            ? (data[3 /* fare */] <23.303322f ? 0.029665114f : -0.056790624f)
            : (data[2 /* age */] <21.685114f ? -0.044024523f : 0.012766739f))
          : -0.10896477f))
      : (data[2 /* age */] <0.32262444f
        ? (data[3 /* fare */] <22.014149f
          ? (data[3 /* fare */] <15.392705f
            ? (data[3 /* fare */] <12.987596f ? -0.056258947f : 0.03895519f)
            : -0.12136817f)
          : (data[0 /* pclass */] <1.0f
            ? (data[3 /* fare */] <31.975489f ? 0.0020838145f : -0.05774825f)
            : 0.01925445f))
        : (data[2 /* age */] <14.172794f
          ? (data[0 /* pclass */] <1.5f
            ? 0.17481206f
            : (data[3 /* fare */] <19.371063f ? 0.13368946f : -0.05706418f))
          : (data[2 /* age */] <19.572681f
            ? (data[3 /* fare */] <8.005145f ? -0.121640794f : -0.053893816f)
            : (data[0 /* pclass */] != 1.0f ? -0.0059548914f : -0.052647285f)))));
    return pred;
  }
}

class MyModel_Forest_21 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_21_class_0.score0(fdata);
  }
}
class MyModel_Tree_21_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[3 /* fare */] <22.549353f
          ? (data[3 /* fare */] <19.113403f
            ? (data[3 /* fare */] <13.258981f ? 0.004611505f : 0.12211288f)
            : -0.056821957f)
          : (data[2 /* age */] <59.57553f
            ? (data[2 /* age */] <52.243176f ? 0.07420885f : 0.11881705f)
            : -0.020101815f))
        : (data[2 /* age */] <27.419296f
          ? (data[3 /* fare */] <23.431253f
            ? (data[3 /* fare */] <8.053223f ? 0.035805974f : -0.0020160822f)
            : (data[3 /* fare */] <31.357914f ? -0.094665386f : 0.010336174f))
          : (data[2 /* age */] <30.754988f
            ? -0.07068659f
            : (data[3 /* fare */] <15.689064f ? -0.030057909f : 0.070949204f))))
      : (data[3 /* fare */] <135.08682f
        ? (data[3 /* fare */] <86.27615f
          ? (data[3 /* fare */] <7.4143567f
            ? (data[2 /* age */] <27.71873f ? -0.027158028f : -0.09533451f)
            : (data[3 /* fare */] <64.45984f ? -0.008888072f : -0.049234968f))
          : 0.06296813f)
        : (data[3 /* fare */] <216.13501f ? -0.10979667f : -0.0019399929f)));
    return pred;
  }
}

class MyModel_Forest_22 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_22_class_0.score0(fdata);
  }
}
class MyModel_Tree_22_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[3 /* fare */] <15.009647f
        ? (data[3 /* fare */] <14.2675705f
          ? (data[3 /* fare */] <7.278579f
            ? 0.096417084f
            : (data[3 /* fare */] <10.853512f ? -0.007925032f : 0.056658957f))
          : -0.13467185f)
        : (data[3 /* fare */] <16.952303f
          ? (data[3 /* fare */] <15.6457615f ? 0.022101805f : 0.094360426f)
          : (data[0 /* pclass */] <1.5f
            ? (data[3 /* fare */] <32.86654f ? 0.02163362f : 0.08724839f)
            : (data[2 /* age */] <1.3515954f ? 0.047822665f : -0.032005172f))))
      : (data[0 /* pclass */] <0.5f
        ? (data[3 /* fare */] <26.016722f
          ? -0.05303513f
          : (data[3 /* fare */] <37.414673f
            ? (data[2 /* age */] <54.050797f ? 0.05266802f : -0.03618778f)
            : (data[3 /* fare */] <52.255753f ? -0.082697175f : 0.008283956f)))
        : (data[2 /* age */] <32.231102f
          ? (data[2 /* age */] <28.866882f
            ? (data[2 /* age */] <27.529371f ? -0.012330924f : -0.12633005f)
            : (data[2 /* age */] <29.503298f ? 0.08903965f : 0.011114163f))
          : (data[2 /* age */] <36.310097f
            ? (data[0 /* pclass */] <1.5f ? -0.051740132f : -0.11398643f)
            : (data[2 /* age */] <39.549072f ? 0.03573843f : -0.066683054f)))));
    return pred;
  }
}

class MyModel_Forest_23 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_23_class_0.score0(fdata);
  }
}
class MyModel_Tree_23_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[3 /* fare */] <15.009647f
        ? (data[3 /* fare */] <14.2675705f
          ? (data[3 /* fare */] <7.278579f
            ? 0.09073165f
            : (data[3 /* fare */] <10.853512f ? -0.007128867f : 0.05198736f))
          : -0.12268f)
        : (data[3 /* fare */] <20.837612f
          ? (data[2 /* age */] <1.6478193f
            ? 0.09172487f
            : (data[2 /* age */] <21.238075f ? -0.02614647f : 0.064155936f))
          : (data[0 /* pclass */] <1.5f
            ? (data[3 /* fare */] <36.354042f ? 0.015721822f : 0.08419195f)
            : (data[2 /* age */] <5.6094065f ? 0.018067569f : -0.071915f))))
      : (data[2 /* age */] <0.32262444f
        ? (data[3 /* fare */] <28.018007f
          ? (data[3 /* fare */] <7.004502f
            ? -0.11764705f
            : (data[3 /* fare */] <23.67465f ? -0.029748635f : -0.052345432f))
          : (data[3 /* fare */] <46.72179f ? 0.03707994f : -0.025975134f))
        : (data[2 /* age */] <14.172794f
          ? (data[0 /* pclass */] <1.5f
            ? 0.16259982f
            : (data[3 /* fare */] <19.371063f ? 0.11958887f : -0.05156027f))
          : (data[2 /* age */] <19.572681f
            ? (data[3 /* fare */] <8.005145f ? -0.11862563f : -0.049243055f)
            : (data[0 /* pclass */] != 1.0f ? -0.00257006f : -0.04703743f)))));
    return pred;
  }
}

class MyModel_Forest_24 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_24_class_0.score0(fdata);
  }
}
class MyModel_Tree_24_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[3 /* fare */] <22.014149f
        ? (data[3 /* fare */] <20.762012f
          ? (data[3 /* fare */] <18.353699f
            ? (data[2 /* age */] <17.838568f ? 0.023029385f : -0.006800287f)
            : 0.08767911f)
          : -0.1472653f)
        : (data[3 /* fare */] <23.929441f
          ? 0.08634221f
          : (data[0 /* pclass */] <1.5f
            ? (data[2 /* age */] <59.57553f ? 0.06785586f : -0.033545956f)
            : (data[2 /* age */] <5.6094065f ? 0.017489135f : -0.061802953f))))
      : (data[3 /* fare */] <135.08682f
        ? (data[3 /* fare */] <52.24061f
          ? (data[3 /* fare */] <39.996716f
            ? (data[0 /* pclass */] <0.5f ? 0.01689691f : -0.017560065f)
            : (data[2 /* age */] <37.67707f ? -0.120623045f : -0.06493124f))
          : (data[3 /* fare */] <58.66712f
            ? 0.09157247f
            : (data[3 /* fare */] <80.58757f ? -0.047326278f : 0.04641644f)))
        : (data[3 /* fare */] <216.13501f ? -0.105260715f : -0.003276749f)));
    return pred;
  }
}

class MyModel_Forest_25 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_25_class_0.score0(fdata);
  }
}
class MyModel_Tree_25_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[3 /* fare */] <15.009647f
        ? (data[3 /* fare */] <14.2675705f
          ? (data[3 /* fare */] <7.7484274f
            ? (data[2 /* age */] <16.5f ? 0.07557663f : 0.029356645f)
            : (data[2 /* age */] <19.40625f ? 0.030395325f : -0.020243768f))
          : -0.11348002f)
        : (data[3 /* fare */] <16.952303f
          ? (data[3 /* fare */] <15.6457615f ? 0.012103129f : 0.08485107f)
          : (data[0 /* pclass */] <1.5f
            ? (data[2 /* age */] <59.41147f ? 0.05642042f : -0.029502472f)
            : (data[2 /* age */] <23.27216f ? -0.029072087f : 0.03571836f))))
      : (data[2 /* age */] <49.516777f
        ? (data[2 /* age */] <47.49948f
          ? (data[2 /* age */] <45.288567f
            ? (data[3 /* fare */] <56.036015f ? -0.0102761295f : 0.018303828f)
            : -0.11889599f)
          : 0.08613042f)
        : (data[2 /* age */] <51.481518f
          ? -0.07703398f
          : (data[2 /* age */] <54.489326f
            ? 0.030428903f
            : (data[2 /* age */] <59.47188f ? -0.07926537f : -0.033302244f)))));
    return pred;
  }
}

class MyModel_Forest_26 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_26_class_0.score0(fdata);
  }
}
class MyModel_Tree_26_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[3 /* fare */] <22.014149f
        ? (data[3 /* fare */] <20.762012f
          ? (data[3 /* fare */] <18.353699f
            ? (data[2 /* age */] <17.838568f ? 0.018571408f : -0.005697876f)
            : 0.08005448f)
          : -0.13045047f)
        : (data[3 /* fare */] <23.929441f
          ? 0.08062478f
          : (data[0 /* pclass */] <1.5f
            ? (data[2 /* age */] <24.380234f ? 0.09120012f : 0.035239715f)
            : (data[3 /* fare */] <31.630146f ? 0.0067691067f : -0.107513145f))))
      : (data[2 /* age */] <0.32262444f
        ? (data[3 /* fare */] <22.014149f
          ? (data[3 /* fare */] <15.392705f
            ? (data[3 /* fare */] <12.987596f ? -0.046760097f : 0.04380986f)
            : -0.11750981f)
          : (data[3 /* fare */] <30.041916f
            ? 0.016418079f
            : (data[3 /* fare */] <54.727303f ? -0.031874135f : -0.00974825f)))
        : (data[2 /* age */] <9.504198f
          ? (data[0 /* pclass */] <1.5f
            ? 0.15514652f
            : (data[3 /* fare */] <24.036625f ? 0.09672312f : -0.06929122f))
          : (data[0 /* pclass */] != 1.0f
            ? (data[2 /* age */] <24.218752f ? -0.023556529f : 0.0034358208f)
            : (data[2 /* age */] <18.75f ? -0.11596438f : -0.038613167f)))));
    return pred;
  }
}

class MyModel_Forest_27 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_27_class_0.score0(fdata);
  }
}
class MyModel_Tree_27_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[2 /* age */] <3.519075f
        ? (data[2 /* age */] <1.4958644f
          ? (data[3 /* fare */] <15.117774f
            ? (data[3 /* fare */] <7.9649477f ? 0.031172983f : -0.10480204f)
            : (data[3 /* fare */] <23.330463f ? 0.07409091f : -0.010567364f))
          : -0.16857418f)
        : (data[2 /* age */] <6.4919257f
          ? 0.16452865f
          : (data[0 /* pclass */] <1.5f
            ? (data[2 /* age */] <56.593754f ? 0.05094293f : -0.024120979f)
            : (data[2 /* age */] <14.546876f ? -0.08280351f : 0.0045310953f))))
      : (data[3 /* fare */] <135.08682f
        ? (data[3 /* fare */] <52.24061f
          ? (data[3 /* fare */] <39.996716f
            ? (data[0 /* pclass */] <0.5f ? 0.01689798f : -0.01390819f)
            : (data[2 /* age */] <37.67707f ? -0.11793263f : -0.061723214f))
          : (data[3 /* fare */] <58.66712f
            ? 0.08201635f
            : (data[3 /* fare */] <75.848015f ? -0.06816217f : 0.029330604f)))
        : (data[3 /* fare */] <216.13501f ? -0.10103057f : -0.0022581753f)));
    return pred;
  }
}

class MyModel_Forest_28 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_28_class_0.score0(fdata);
  }
}
class MyModel_Tree_28_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[3 /* fare */] <26.016722f
        ? (data[3 /* fare */] <7.2768245f
          ? 0.08259662f
          : (data[2 /* age */] <36.492203f
            ? (data[2 /* age */] <32.5191f ? -2.8863936E-4f : 0.09086744f)
            : (data[2 /* age */] <44.568798f ? -0.13840295f : 0.01048928f)))
        : (data[2 /* age */] <2.5364907f
          ? (data[3 /* fare */] <62.326195f ? 0.051628336f : -0.08561561f)
          : (data[0 /* pclass */] != 1.0f
            ? (data[3 /* fare */] <49.034966f ? -1.5200561E-4f : 0.081431575f)
            : (data[3 /* fare */] <33.84499f ? 0.11119475f : 0.105816446f))))
      : (data[2 /* age */] <36.808937f
        ? (data[0 /* pclass */] <0.5f
          ? (data[2 /* age */] <33.533203f
            ? (data[3 /* fare */] <124.07975f ? 0.014252147f : -0.058338497f)
            : 0.12468043f)
          : (data[3 /* fare */] <62.039875f
            ? (data[3 /* fare */] <44.106472f ? -0.0085166255f : 0.07383794f)
            : -0.11321882f))
        : (data[2 /* age */] <41.4486f
          ? (data[0 /* pclass */] <1.5f
            ? (data[3 /* fare */] <28.774221f ? -0.12089819f : -0.045407064f)
            : (data[2 /* age */] <39.46875f ? 0.04060821f : -0.11304768f))
          : (data[2 /* age */] <45.213387f
            ? (data[2 /* age */] <43.48117f ? 0.0022281369f : 0.04937256f)
            : (data[3 /* fare */] <90.406265f ? -0.018872065f : -0.09549501f)))));
    return pred;
  }
}

class MyModel_Forest_29 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_29_class_0.score0(fdata);
  }
}
class MyModel_Tree_29_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[3 /* fare */] <26.016722f
      ? (data[3 /* fare */] <23.348991f
        ? (data[3 /* fare */] <21.844076f
          ? (data[3 /* fare */] <20.820137f
            ? (data[3 /* fare */] <18.380276f ? -0.005846393f : 0.07399987f)
            : (data[2 /* age */] <27.85419f ? -0.19549592f : -0.011058477f))
          : 0.14741585f)
        : (data[0 /* pclass */] <1.5f
          ? (data[2 /* age */] <24.523441f
            ? 0.096286595f
            : (data[2 /* age */] <31.000065f ? -0.11530925f : -0.055502266f))
          : -0.10777875f))
      : (data[3 /* fare */] <254.92557f
        ? (data[3 /* fare */] <135.22821f
          ? (data[3 /* fare */] <116.92328f
            ? (data[3 /* fare */] <27.66677f ? 0.04516533f : 0.00950674f)
            : 0.17497744f)
          : (data[1 /* sex */] <0.5f
            ? (data[3 /* fare */] <153.11572f ? -0.114766166f : 0.037981734f)
            : -0.10565033f))
        : 0.10390631f));
    return pred;
  }
}

class MyModel_Forest_30 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_30_class_0.score0(fdata);
  }
}
class MyModel_Tree_30_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[2 /* age */] <3.519075f
        ? (data[2 /* age */] <1.4958644f
          ? (data[3 /* fare */] <15.117774f
            ? (data[3 /* fare */] <7.9649477f ? 0.028504286f : -0.09310063f)
            : (data[3 /* fare */] <23.330463f ? 0.06653307f : -0.003587189f))
          : -0.14432386f)
        : (data[2 /* age */] <6.4919257f
          ? 0.15513074f
          : (data[3 /* fare */] <50.19822f
            ? (data[2 /* age */] <17.78125f ? 0.032492485f : -6.0693646E-4f)
            : (data[3 /* fare */] <151.2894f ? 0.106686965f : 0.024529357f))))
      : (data[2 /* age */] <36.808937f
        ? (data[2 /* age */] <0.76074886f
          ? (data[0 /* pclass */] != 1.0f
            ? (data[3 /* fare */] <28.440626f ? -0.03392344f : 0.0043584104f)
            : 0.016994832f)
          : (data[2 /* age */] <3.552878f
            ? 0.12695819f
            : (data[0 /* pclass */] <0.5f ? 0.032683995f : -0.009206931f)))
        : (data[2 /* age */] <41.4486f
          ? (data[0 /* pclass */] <1.5f
            ? (data[2 /* age */] <39.46875f ? -0.075302936f : -0.063296594f)
            : (data[2 /* age */] <39.46875f ? 0.03700701f : -0.11161275f))
          : (data[2 /* age */] <49.580536f
            ? (data[2 /* age */] <47.507736f ? -0.016018616f : 0.07829387f)
            : (data[2 /* age */] <51.48175f ? -0.07044048f : -0.02566511f)))));
    return pred;
  }
}

class MyModel_Forest_31 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_31_class_0.score0(fdata);
  }
}
class MyModel_Tree_31_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[3 /* fare */] <26.016722f
        ? (data[3 /* fare */] <7.2768245f
          ? 0.07767719f
          : (data[2 /* age */] <36.492203f
            ? (data[2 /* age */] <32.5191f ? -8.004096E-5f : 0.08365115f)
            : (data[2 /* age */] <44.568798f ? -0.121280484f : 0.010804741f)))
        : (data[3 /* fare */] <149.49452f
          ? (data[2 /* age */] <56.935883f
            ? (data[0 /* pclass */] <1.5f ? 0.078202285f : -0.011572402f)
            : 0.115925245f)
          : (data[3 /* fare */] <224.61267f ? -0.071309365f : 0.10682709f)))
      : (data[2 /* age */] <32.287132f
        ? (data[2 /* age */] <30.726887f
          ? (data[2 /* age */] <27.521313f
            ? (data[2 /* age */] <24.760029f ? -0.008754661f : 0.04345117f)
            : (data[2 /* age */] <28.754677f ? -0.088443816f : -0.005963478f))
          : (data[3 /* fare */] <23.62891f ? 0.03209258f : 0.10838407f))
        : (data[2 /* age */] <33.498592f
          ? -0.12490167f
          : (data[3 /* fare */] <116.0746f
            ? (data[3 /* fare */] <52.596302f ? -0.0136590665f : -0.04814736f)
            : 0.06968275f))));
    return pred;
  }
}

class MyModel_Forest_32 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_32_class_0.score0(fdata);
  }
}
class MyModel_Tree_32_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[2 /* age */] <56.44923f
          ? (data[2 /* age */] <27.598347f
            ? (data[2 /* age */] <24.471592f ? 0.044443306f : -0.10070643f)
            : (data[2 /* age */] <35.364426f ? 0.07076378f : 0.041277684f))
          : -0.043625064f)
        : (data[2 /* age */] <27.419296f
          ? (data[2 /* age */] <21.45779f
            ? (data[2 /* age */] <18.297394f ? 0.00478616f : -0.076602936f)
            : (data[3 /* fare */] <10.675001f ? 0.011786305f : 0.0909956f))
          : (data[3 /* fare */] <8.221875f
            ? -0.07198679f
            : (data[2 /* age */] <38.664062f ? 0.030282708f : -0.041880433f))))
      : (data[3 /* fare */] <135.08682f
        ? (data[3 /* fare */] <86.27615f
          ? (data[2 /* age */] <32.075504f
            ? (data[2 /* age */] <30.58759f ? -0.0044804118f : 0.050523654f)
            : (data[2 /* age */] <33.573147f ? -0.12214422f : -0.017636785f))
          : 0.042176515f)
        : (data[3 /* fare */] <216.13501f ? -0.087212615f : -0.0055996175f)));
    return pred;
  }
}

class MyModel_Forest_33 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_33_class_0.score0(fdata);
  }
}
class MyModel_Tree_33_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[3 /* fare */] <254.91383f
      ? (data[3 /* fare */] <216.57718f
        ? (data[3 /* fare */] <6.768037f
          ? (data[3 /* fare */] <3.569082f ? -0.0038174249f : -0.16497733f)
          : (data[0 /* pclass */] <0.5f
            ? (data[3 /* fare */] <134.75937f ? 0.021186633f : -0.038794518f)
            : (data[3 /* fare */] <67.611305f ? -0.0018474457f : -0.11098048f)))
        : -0.12240541f)
      : 0.089460224f);
    return pred;
  }
}

class MyModel_Forest_34 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_34_class_0.score0(fdata);
  }
}
class MyModel_Tree_34_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[3 /* fare */] <52.283604f
      ? (data[3 /* fare */] <39.62117f
        ? (data[3 /* fare */] <35.287605f
          ? (data[3 /* fare */] <31.428022f
            ? (data[3 /* fare */] <29.954836f ? -0.0031840906f : 0.06698268f)
            : (data[2 /* age */] <23.243515f ? -0.04519262f : -0.16732043f))
          : (data[2 /* age */] <29.480492f ? 0.10053394f : -4.4777186E-4f))
        : (data[1 /* sex */] <0.5f
          ? 0.028392732f
          : (data[2 /* age */] <37.914066f
            ? (data[0 /* pclass */] <0.5f ? -0.120093f : -0.11234298f)
            : -0.056741394f)))
      : (data[3 /* fare */] <64.41371f
        ? (data[2 /* age */] <32.445824f
          ? (data[1 /* sex */] <0.5f ? 0.104353316f : 0.10180026f)
          : (data[2 /* age */] <45.543797f ? 0.06893948f : -0.026812749f))
        : (data[3 /* fare */] <76.66141f
          ? (data[1 /* sex */] <0.5f
            ? 0.038694736f
            : (data[2 /* age */] <19.25f ? -0.111149326f : -0.12490205f))
          : (data[3 /* fare */] <134.52354f
            ? (data[3 /* fare */] <116.462814f ? 0.01919519f : 0.16160719f)
            : (data[3 /* fare */] <255.53944f ? -0.055268403f : 0.08128184f)))));
    return pred;
  }
}

class MyModel_Forest_35 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_35_class_0.score0(fdata);
  }
}
class MyModel_Tree_35_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[2 /* age */] <3.519075f
        ? (data[2 /* age */] <1.4958644f
          ? (data[3 /* fare */] <15.117774f
            ? (data[3 /* fare */] <7.9649477f ? 0.025570048f : -0.08394278f)
            : (data[3 /* fare */] <23.330463f ? 0.061497584f : -0.00819089f))
          : -0.12748343f)
        : (data[2 /* age */] <6.4919257f
          ? 0.14459114f
          : (data[2 /* age */] <11.650728f
            ? -0.062883876f
            : (data[2 /* age */] <16.678017f ? 0.08296118f : 0.008829192f))))
      : (data[2 /* age */] <0.32262444f
        ? (data[3 /* fare */] <28.018007f
          ? (data[3 /* fare */] <23.421303f
            ? (data[3 /* fare */] <8.051073f ? -0.040942065f : 0.023230916f)
            : -0.059437428f)
          : (data[3 /* fare */] <46.72179f ? 0.026162704f : -0.019726533f))
        : (data[2 /* age */] <14.172794f
          ? (data[0 /* pclass */] <1.5f
            ? 0.1431989f
            : (data[3 /* fare */] <25.446163f ? 0.08933056f : -0.07668091f))
          : (data[2 /* age */] <19.572681f
            ? (data[3 /* fare */] <16.01029f ? -0.042495042f : -0.10842699f)
            : (data[2 /* age */] <20.51686f ? 0.079583906f : -0.007286831f)))));
    return pred;
  }
}

class MyModel_Forest_36 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_36_class_0.score0(fdata);
  }
}
class MyModel_Tree_36_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[3 /* fare */] <26.016722f
      ? (data[3 /* fare */] <23.348991f
        ? (data[3 /* fare */] <21.844076f
          ? (data[3 /* fare */] <20.820137f
            ? (data[3 /* fare */] <18.380276f ? -0.0036284172f : 0.06339984f)
            : (data[2 /* age */] <27.85419f ? -0.17738722f : -0.01336709f))
          : 0.13507709f)
        : (data[0 /* pclass */] <1.5f
          ? (data[2 /* age */] <24.523441f
            ? 0.09081234f
            : (data[2 /* age */] <31.000065f ? -0.106735915f : -0.05113218f))
          : -0.100460075f))
      : (data[3 /* fare */] <26.96655f
        ? (data[3 /* fare */] <26.469723f
          ? 0.13418424f
          : (data[2 /* age */] <43.476566f ? -0.0087375175f : 0.034201693f))
        : (data[3 /* fare */] <28.8625f
          ? (data[2 /* age */] <30.520817f ? -0.09952353f : 0.017327914f)
          : (data[2 /* age */] <60.51758f
            ? (data[3 /* fare */] <251.78458f ? 0.009836932f : 0.11105415f)
            : -0.049994033f))));
    return pred;
  }
}

class MyModel_Forest_37 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_37_class_0.score0(fdata);
  }
}
class MyModel_Tree_37_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[2 /* age */] <56.44923f
          ? (data[2 /* age */] <27.598347f
            ? (data[2 /* age */] <24.471592f ? 0.040675115f : -0.0771732f)
            : (data[2 /* age */] <35.364426f ? 0.06795897f : 0.03748369f))
          : -0.0394404f)
        : (data[2 /* age */] <24.457056f
          ? (data[2 /* age */] <21.515644f
            ? (data[2 /* age */] <18.179873f ? 0.004207404f : -0.06895828f)
            : (data[2 /* age */] <22.505505f ? 0.07498759f : 0.029168466f))
          : (data[3 /* fare */] <8.221875f
            ? (data[2 /* age */] <29.453125f ? -0.051128127f : -0.04544881f)
            : (data[3 /* fare */] <14.265333f ? 0.04723589f : -0.016877253f))))
      : (data[2 /* age */] <36.808937f
        ? (data[2 /* age */] <0.76074886f
          ? (data[0 /* pclass */] != 1.0f
            ? (data[3 /* fare */] <28.440626f ? -0.02752046f : 0.0028430272f)
            : 0.015706781f)
          : (data[2 /* age */] <3.552878f
            ? 0.11434372f
            : (data[0 /* pclass */] <0.5f ? 0.025864096f : -0.006664038f)))
        : (data[3 /* fare */] <91.058525f
          ? (data[3 /* fare */] <75.763535f
            ? (data[2 /* age */] <38.34375f ? -0.08961995f : -0.017344559f)
            : 0.04121532f)
          : -0.06539696f)));
    return pred;
  }
}

class MyModel_Forest_38 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_38_class_0.score0(fdata);
  }
}
class MyModel_Tree_38_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[3 /* fare */] <26.016722f
        ? (data[3 /* fare */] <7.2768245f
          ? 0.07608346f
          : (data[2 /* age */] <36.492203f
            ? (data[2 /* age */] <32.5191f ? -0.0013920922f : 0.07514034f)
            : (data[2 /* age */] <44.568798f ? -0.112592846f : 0.010260845f)))
        : (data[3 /* fare */] <149.49452f
          ? (data[2 /* age */] <56.935883f
            ? (data[0 /* pclass */] <1.5f ? 0.071022235f : -0.0118547855f)
            : 0.11478069f)
          : (data[2 /* age */] <27.606468f
            ? -0.101598896f
            : (data[3 /* fare */] <216.37753f ? 0.11076657f : -0.040456302f))))
      : (data[3 /* fare */] <135.08682f
        ? (data[3 /* fare */] <52.24061f
          ? (data[3 /* fare */] <37.752f
            ? (data[3 /* fare */] <28.314f ? -0.0064897574f : 0.024454314f)
            : (data[3 /* fare */] <39.866936f ? -0.04468951f : -0.086539045f))
          : (data[3 /* fare */] <64.12966f
            ? (data[2 /* age */] <34.421875f ? 0.09165963f : -0.0015314805f)
            : (data[3 /* fare */] <76.22456f ? -0.11763168f : 0.014839154f)))
        : (data[2 /* age */] <33.787094f ? -0.06690695f : -0.005201316f)));
    return pred;
  }
}

class MyModel_Forest_39 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_39_class_0.score0(fdata);
  }
}
class MyModel_Tree_39_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* age */] <0.40058663f
      ? (data[3 /* fare */] <7.004502f
        ? -0.11327033f
        : (data[3 /* fare */] <7.86591f
          ? (data[3 /* fare */] <7.674681f
            ? (data[3 /* fare */] <7.2403326f ? 0.017394504f : -0.16682115f)
            : (data[1 /* sex */] <0.5f ? 0.038536686f : 0.06982472f))
          : (data[3 /* fare */] <14.730257f
            ? (data[3 /* fare */] <14.087971f ? -0.025372531f : -0.14004105f)
            : (data[0 /* pclass */] <1.5f ? -0.024726126f : 0.02310125f))))
      : (data[2 /* age */] <1.4888599f
        ? (data[2 /* age */] <0.95906216f ? 0.11984097f : 0.065126844f)
        : (data[2 /* age */] <2.4089124f
          ? -0.06960964f
          : (data[2 /* age */] <5.4398146f
            ? (data[1 /* sex */] <0.5f ? 0.06609953f : 0.09688474f)
            : (data[0 /* pclass */] <0.5f ? 0.013939011f : -0.0056225355f)))));
    return pred;
  }
}

class MyModel_Forest_40 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_40_class_0.score0(fdata);
  }
}
class MyModel_Tree_40_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[3 /* fare */] <254.91383f
      ? (data[3 /* fare */] <135.17404f
        ? (data[3 /* fare */] <116.69322f
          ? (data[3 /* fare */] <92.07825f
            ? (data[3 /* fare */] <85.604f ? -3.634422E-4f : 0.10907706f)
            : -0.07421213f)
          : 0.15446891f)
        : (data[1 /* sex */] <0.5f
          ? (data[3 /* fare */] <152.67867f ? -0.08209116f : 0.038159654f)
          : -0.0944702f))
      : 0.06896088f);
    return pred;
  }
}

class MyModel_Forest_41 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_41_class_0.score0(fdata);
  }
}
class MyModel_Tree_41_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[2 /* age */] <3.519075f
        ? (data[2 /* age */] <1.4958644f
          ? (data[3 /* fare */] <15.117774f
            ? (data[3 /* fare */] <7.9649477f ? 0.021705627f : -0.07242815f)
            : (data[3 /* fare */] <23.330463f ? 0.05250666f : -0.007550361f))
          : -0.11031262f)
        : (data[2 /* age */] <6.4919257f
          ? 0.13360216f
          : (data[2 /* age */] <14.6374035f
            ? (data[2 /* age */] <10.520366f ? -0.053636506f : -0.0249892f)
            : (data[2 /* age */] <16.554985f ? 0.13926828f : 0.0065580197f))))
      : (data[2 /* age */] <36.808937f
        ? (data[2 /* age */] <0.76074886f
          ? (data[0 /* pclass */] != 1.0f
            ? (data[3 /* fare */] <28.440626f ? -0.023664571f : 0.0043153437f)
            : 0.01854549f)
          : (data[2 /* age */] <9.555956f
            ? (data[3 /* fare */] <24.015434f ? 0.10887612f : 0.029608175f)
            : (data[2 /* age */] <19.449472f ? -0.038238868f : 0.004337928f)))
        : (data[3 /* fare */] <91.058525f
          ? (data[2 /* age */] <47.414062f
            ? (data[3 /* fare */] <32.343754f ? -0.014856528f : -0.072919436f)
            : (data[2 /* age */] <49.70526f ? 0.105759144f : -0.0214834f))
          : -0.06279105f)));
    return pred;
  }
}

class MyModel_Forest_42 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_42_class_0.score0(fdata);
  }
}
class MyModel_Tree_42_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* pclass */] <0.5f
      ? (data[2 /* age */] <60.50945f
        ? (data[2 /* age */] <50.49973f
          ? (data[3 /* fare */] <254.16336f
            ? (data[3 /* fare */] <135.02428f ? 0.010443175f : -0.03876069f)
            : 0.09861284f)
          : (data[2 /* age */] <53.505676f
            ? 0.102842994f
            : (data[1 /* sex */] <0.5f ? 0.11071796f : -0.011973515f)))
        : (data[3 /* fare */] <55.035374f ? -0.017011322f : -0.09465301f))
      : (data[2 /* age */] <45.22886f
        ? (data[2 /* age */] <44.524765f
          ? (data[2 /* age */] <34.301617f
            ? (data[3 /* fare */] <12.632813f ? 0.0077559385f : -0.010440218f)
            : (data[3 /* fare */] <12.632813f ? -0.072775654f : 0.007969469f))
          : 0.085599236f)
        : (data[2 /* age */] <60.738304f
          ? (data[2 /* age */] <54.48822f
            ? (data[0 /* pclass */] <1.5f ? -0.023305405f : -0.07793024f)
            : -0.17186333f)
          : 0.0642946f)));
    return pred;
  }
}

class MyModel_Forest_43 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_43_class_0.score0(fdata);
  }
}
class MyModel_Tree_43_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[3 /* fare */] <52.283604f
      ? (data[3 /* fare */] <39.62117f
        ? (data[3 /* fare */] <6.809889f
          ? (data[3 /* fare */] <3.5911522f ? 0.0028922395f : -0.16892968f)
          : (data[3 /* fare */] <7.83458f
            ? (data[3 /* fare */] <7.788817f ? 0.00888025f : 0.20393588f)
            : (data[3 /* fare */] <8.82725f ? -0.026347674f : 0.002173985f)))
        : (data[1 /* sex */] <0.5f
          ? 0.017899418f
          : (data[2 /* age */] <37.914066f
            ? (data[0 /* pclass */] <0.5f ? -0.117018394f : -0.11052479f)
            : -0.047256444f)))
      : (data[3 /* fare */] <64.41371f
        ? (data[2 /* age */] <42.56447f
          ? (data[1 /* sex */] <0.5f ? 0.10337678f : 0.07778025f)
          : -0.012019097f)
        : (data[1 /* sex */] <0.5f
          ? (data[2 /* age */] <7.95576f
            ? -0.064432226f
            : (data[3 /* fare */] <215.27469f ? 0.0795478f : 0.002791203f))
          : (data[2 /* age */] <17.634468f
            ? 0.04204171f
            : (data[2 /* age */] <24.589268f ? -0.11301114f : -0.013865881f)))));
    return pred;
  }
}

class MyModel_Forest_44 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_44_class_0.score0(fdata);
  }
}
class MyModel_Tree_44_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* age */] <0.40058663f
      ? (data[3 /* fare */] <7.004502f
        ? -0.11184343f
        : (data[3 /* fare */] <7.86591f
          ? (data[3 /* fare */] <7.674681f
            ? (data[3 /* fare */] <7.2403326f ? 0.01575005f : -0.16424282f)
            : (data[1 /* sex */] <0.5f ? 0.030779183f : 0.059355248f))
          : (data[3 /* fare */] <14.730257f
            ? (data[3 /* fare */] <14.087971f ? -0.019291451f : -0.13293438f)
            : (data[0 /* pclass */] <1.5f ? -0.021572707f : 0.02009f))))
      : (data[2 /* age */] <1.4888599f
        ? (data[2 /* age */] <0.95906216f ? 0.11185757f : 0.06071214f)
        : (data[2 /* age */] <16.516384f
          ? (data[3 /* fare */] <16.01029f
            ? (data[3 /* fare */] <13.602886f ? 0.109027006f : 0.0058320086f)
            : (data[0 /* pclass */] <1.5f ? 0.08132814f : -0.0648912f))
          : (data[2 /* age */] <18.74823f
            ? (data[3 /* fare */] <8.005145f ? -0.08800868f : -0.018265111f)
            : (data[3 /* fare */] <8.005145f ? 0.01191984f : -0.00404945f)))));
    return pred;
  }
}

class MyModel_Forest_45 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_45_class_0.score0(fdata);
  }
}
class MyModel_Tree_45_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* pclass */] <0.5f
      ? (data[2 /* age */] <60.50945f
        ? (data[2 /* age */] <47.473534f
          ? (data[2 /* age */] <45.291183f
            ? (data[3 /* fare */] <252.16208f ? 0.008205663f : 0.09225613f)
            : -0.105486356f)
          : (data[2 /* age */] <49.479725f
            ? 0.10049535f
            : (data[2 /* age */] <51.53447f ? -0.07959635f : 0.04522451f)))
        : (data[3 /* fare */] <55.035374f ? -0.015060136f : -0.089502744f))
      : (data[2 /* age */] <45.22886f
        ? (data[2 /* age */] <44.524765f
          ? (data[2 /* age */] <39.499825f
            ? (data[3 /* fare */] <67.1836f ? 3.2204992E-4f : -0.10813857f)
            : (data[3 /* fare */] <19.52344f ? -0.0057355016f : -0.13414691f))
          : 0.07608952f)
        : (data[2 /* age */] <60.738304f
          ? (data[2 /* age */] <54.48822f
            ? (data[0 /* pclass */] <1.5f ? -0.021090576f : -0.07390815f)
            : -0.16006368f)
          : 0.056006633f)));
    return pred;
  }
}

class MyModel_Forest_46 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_46_class_0.score0(fdata);
  }
}
class MyModel_Tree_46_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[0 /* pclass */] <1.5f
        ? (data[2 /* age */] <56.44923f
          ? (data[2 /* age */] <38.444542f
            ? (data[2 /* age */] <35.51268f ? 0.03179686f : -0.10897182f)
            : (data[3 /* fare */] <26.182167f ? 0.07282784f : 0.052799996f))
          : -0.03985125f)
        : (data[2 /* age */] <24.457056f
          ? (data[2 /* age */] <21.515644f
            ? (data[2 /* age */] <18.179873f ? 0.0023083729f : -0.06136346f)
            : (data[2 /* age */] <22.505505f ? 0.06663025f : 0.026432637f))
          : (data[3 /* fare */] <8.221875f
            ? (data[2 /* age */] <29.453125f ? -0.0463494f : -0.044728417f)
            : (data[3 /* fare */] <13.358814f ? 0.050915685f : -0.013138221f))))
      : (data[3 /* fare */] <135.08682f
        ? (data[2 /* age */] <32.231102f
          ? (data[2 /* age */] <30.860495f
            ? (data[2 /* age */] <27.521584f ? 0.0026169538f : -0.033f)
            : (data[3 /* fare */] <24.167973f ? 0.025389705f : 0.08934507f))
          : (data[2 /* age */] <33.537285f
            ? -0.120165765f
            : (data[0 /* pclass */] <0.5f ? 0.0054113776f : -0.034554623f)))
        : (data[2 /* age */] <33.787094f ? -0.06324484f : -0.0016875044f)));
    return pred;
  }
}

class MyModel_Forest_47 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_47_class_0.score0(fdata);
  }
}
class MyModel_Tree_47_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* age */] <0.40058663f
      ? (data[3 /* fare */] <7.004502f
        ? -0.110688575f
        : (data[3 /* fare */] <7.86591f
          ? (data[3 /* fare */] <7.674681f
            ? (data[3 /* fare */] <7.2403326f ? 0.0137207145f : -0.1595652f)
            : (data[1 /* sex */] <0.5f ? 0.027726164f : 0.050500825f))
          : (data[3 /* fare */] <14.730257f
            ? (data[3 /* fare */] <14.087971f ? -0.017853497f : -0.1290654f)
            : (data[0 /* pclass */] <1.5f ? -0.020587727f : 0.018745614f))))
      : (data[2 /* age */] <1.4888599f
        ? (data[2 /* age */] <0.95906216f ? 0.10498718f : 0.05500273f)
        : (data[2 /* age */] <2.4089124f
          ? -0.06075886f
          : (data[2 /* age */] <5.4398146f
            ? (data[1 /* sex */] <0.5f ? 0.058666874f : 0.08332808f)
            : (data[0 /* pclass */] <0.5f ? 0.01127236f : -0.004533664f)))));
    return pred;
  }
}

class MyModel_Forest_48 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_48_class_0.score0(fdata);
  }
}
class MyModel_Tree_48_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* sex */] <0.5f
      ? (data[2 /* age */] <3.519075f
        ? (data[2 /* age */] <1.4958644f
          ? (data[3 /* fare */] <15.117774f
            ? (data[3 /* fare */] <7.9649477f ? 0.016414838f : -0.059984565f)
            : (data[3 /* fare */] <23.330463f ? 0.04476297f : -0.00720377f))
          : -0.10016104f)
        : (data[2 /* age */] <6.4919257f
          ? 0.12606439f
          : (data[2 /* age */] <14.6374035f
            ? (data[2 /* age */] <10.520366f ? -0.047955763f : -0.029980835f)
            : (data[2 /* age */] <16.554985f ? 0.13010988f : 0.0057979943f))))
      : (data[3 /* fare */] <64.04116f
        ? (data[3 /* fare */] <56.161095f
          ? (data[3 /* fare */] <36.855717f
            ? (data[3 /* fare */] <28.217657f ? -0.0043845396f : 0.022370625f)
            : (data[3 /* fare */] <51.13893f ? -0.0791811f : -0.005095455f))
          : 0.068380855f)
        : (data[2 /* age */] <17.449192f
          ? 0.036585078f
          : (data[2 /* age */] <24.428596f
            ? -0.10615843f
            : (data[3 /* fare */] <113.926636f ? -0.028715383f : 0.016510524f)))));
    return pred;
  }
}

class MyModel_Forest_49 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += MyModel_Tree_49_class_0.score0(fdata);
  }
}
class MyModel_Tree_49_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* age */] <0.40058663f
      ? (data[3 /* fare */] <7.004502f
        ? -0.10954515f
        : (data[3 /* fare */] <7.86591f
          ? (data[3 /* fare */] <7.674681f
            ? (data[3 /* fare */] <7.2403326f ? 0.012471727f : -0.15570603f)
            : (data[1 /* sex */] <0.5f ? 0.023666047f : 0.04423778f))
          : (data[3 /* fare */] <21.594604f
            ? (data[3 /* fare */] <15.165508f ? -0.041328564f : 0.0079665175f)
            : (data[3 /* fare */] <24.812267f ? 0.036664624f : -0.0060699168f))))
      : (data[2 /* age */] <1.4888599f
        ? (data[2 /* age */] <0.95906216f ? 0.097749546f : 0.05386131f)
        : (data[2 /* age */] <16.516384f
          ? (data[3 /* fare */] <16.01029f
            ? (data[3 /* fare */] <13.602886f ? 0.09872213f : 0.005177192f)
            : (data[0 /* pclass */] <1.5f ? 0.075723924f : -0.061959513f))
          : (data[2 /* age */] <18.74823f
            ? (data[3 /* fare */] <8.005145f ? -0.08004993f : -0.016830055f)
            : (data[3 /* fare */] <8.005145f ? 0.012369359f : -0.003923189f)))));
    return pred;
  }
}

